// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require, exports, module) {
    module.exports.getUnicast = function() {
      var array, bin, hex, mac, n, _i, _len;
      hex = '';
      array = new Uint8Array(24);
      window.crypto.getRandomValues(array);
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        n = array[_i];
        hex += n.toString(16);
      }
      mac = hex.slice(0, 12).match(/.{2}/g).join(':');
      bin = ("0000" + (parseInt(mac.charAt(1), 16).toString(2))).slice(-4);
      bin = "" + (bin.slice(0, 3)) + "0";
      return "" + (mac.charAt(0)) + (parseInt(bin, 2).toString(16)) + ":" + (mac.slice(3));
    };
    module.exports.getMulticast = function() {
      var array, bin, hex, mac, n, _i, _len;
      hex = '';
      array = new Uint8Array(24);
      window.crypto.getRandomValues(array);
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        n = array[_i];
        hex += n.toString(16);
      }
      mac = hex.slice(0, 12).match(/.{2}/g).join(':');
      bin = ("0000" + (parseInt(mac.charAt(1), 16).toString(2))).slice(-4);
      bin = "" + (bin.slice(0, 3)) + "1";
      return "" + (mac.charAt(0)) + (parseInt(bin, 2).toString(16)) + ":" + (mac.slice(3));
    };
    return void 0;
  });

}).call(this);
